jobs:
    "Player Sync":
        schedule:
            delay: 2
            period: 2
        steps:
            '1':
                command: "DYNMAP SYNC PLAYERS"
                command-fallback: "LOG Failed to sync players"
    "Config Sync":
        schedule:
            delay: 0
            period: 3600
        steps:
            '1':
                command: "DYNMAP SYNC CONFIG"
                command-fallback: "LOG Failed to sync config"
    "Marker Sync":
        schedule:
            delay: 60
            period: 300
        steps:
            '1':
                command: "DYNMAP SYNC MARKERS"
                command-fallback: "LOG Failed to sync markers"
    "Tiles Sync":
        schedule:
            delay: 80
            period: 300
        steps:
            '1':
                command: "DYNMAP SYNC TILES"
                command-fallback: "LOG Failed to sync tiles"