jobs:
    "Player Sync":
        schedule:
            delay: 2
            period: 2
        steps:
            '1':
                command: "DYNMAP SYNC PLAYERS"
                command-fallback: "LOG Failed to sync players"